### ISSUE TITLE
Another refactor for overall architecture of host module and server

### ISSUE THREAD

**Issue by SmileWuji** [SmileWuji/tea-party-deception#1]
TL;DR.
Before the project becomes any larger, it is possible to move everything in this repo into Python and develop only a CLI server version.

The cards model needs to be "callback based".
Also, originally the purpose of "view template" is to help those java embedded platforms to be easier integrable; however, it looks like such thing is never going to happen.
The view and the host are only communicating through strings (or commands) bulked in the announcer.

**Comment by LeonYuAng3NT** [comment]
Agreed on building a CLI server version, just not sure about what is needed.  If we only want the communication between the view and the host, why not create a message queue to deliver all the strings?  I suspect that using pure strings without any data structures in terms of logging or announcer will be a huge drawback in terms of performance.

**Comment by SmileWuji** [comment]
Definitely, a message queue is required even for the server (or in other words, the logic level of the game itself). The problem is that a game runs on two different computers (or processes), so at the very least we need sockets to connect the two processes.

So at the data transmission level it is better to convert the message queue to strings (or json, which is a typical format of strings) because strings are better for debugging + parsing.

There's follow-up of this issue. The remark of the discussion happened three days ago is that we keep the Java stack and refactor on top of the current version.

**Comment by SmileWuji** [comment]
The refactoring is done. 
The legacy source is kept inside the repo, as a reference implementation for the CLI debug tool.
